apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cnf
data:
  primary.cnf: |
    # Apply this config only on the primary.1
    [mysqld]
    log-bin    
    bind-address = 0.0.0.0
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only    
    bind-address = 0.0.0.0