apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: {{ .Values.containers.image }}
        name: app
        resources: {}
        env:
          - name: DB_HOST
            value: {{ .Values.db_endpoint }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password


